name: Testing

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build container
        run: docker build .
