name: Testing

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  docker-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features -F native-tls -F postgres
      - name: Build container
        run: docker build .
      - name: Run tests
        run: cd tests && ./run_test.sh
